/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VacationRequest {
        /**
          * @default ''
         */
        "apiKey": string;
        /**
          * @default '/widget/request'
         */
        "endpoint": string;
    }
}
declare global {
    interface HTMLVacationRequestElement extends Components.VacationRequest, HTMLStencilElement {
    }
    var HTMLVacationRequestElement: {
        prototype: HTMLVacationRequestElement;
        new (): HTMLVacationRequestElement;
    };
    interface HTMLElementTagNameMap {
        "vacation-request": HTMLVacationRequestElement;
    }
}
declare namespace LocalJSX {
    interface VacationRequest {
        /**
          * @default ''
         */
        "apiKey"?: string;
        /**
          * @default '/widget/request'
         */
        "endpoint"?: string;
    }

    interface VacationRequestAttributes {
        "endpoint": string;
        "apiKey": string;
    }

    interface IntrinsicElements {
        "vacation-request": Omit<VacationRequest, keyof VacationRequestAttributes> & { [K in keyof VacationRequest & keyof VacationRequestAttributes]?: VacationRequest[K] } & { [K in keyof VacationRequest & keyof VacationRequestAttributes as `attr:${K}`]?: VacationRequestAttributes[K] } & { [K in keyof VacationRequest & keyof VacationRequestAttributes as `prop:${K}`]?: VacationRequest[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vacation-request": LocalJSX.IntrinsicElements["vacation-request"] & JSXBase.HTMLAttributes<HTMLVacationRequestElement>;
        }
    }
}
